kind: Template
apiVersion: template.openshift.io/v1
metadata: 
  name: webapp
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata: 
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: "${{REPLICA_COUNT}}"
    selector: 
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    template: 
      metadata: 
        labels: 
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec: 
        containers: 
        - image: ${REPO_NAME}/${IMAGE_NAME}
          name: ${APP_NAME}
          ports: 
          - containerPort: 80
            protocol: TCP
          readinessProbe: 
            timeoutSeconds: 3
            initialDelaySeconds: 3
            httpGet: 
              path: "/"
              port: 80
          livenessProbe: 
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet: 
              path: "/"
              port: 80
- kind: Service
  apiVersion: v1
  metadata: 
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    path: /
    port:
      targetPort: web
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100          
parameters: 
- name: REPO_NAME
  description: "desc"
  required: true
  value: centos
  
- name: APP_NAME
  description: "desc"
  required: true
  value: webapp
  
- name: REPLICA_COUNT
  description: "desc"
  required: true
  value: "1"
  
- name: IMAGE_NAME
  description: "desc"
  required: true
  value: httpd-24-centos7:latest
